### PR TITLE
Fix JSON to struct conversion

### LINKED ISSUE #4736: Json to Struct conversion error
**Description:**
When converting a json object to a struct which is in another package, the following error occurs.
**{msg:"cannot convert 'json' to type 'org.wso2.structs: ...**
However this issue doesn't arise when the struct is defined in the same .bal file where the conversion takes place.

**Steps to reproduce:**
```
public function main (string[] args) {
    json sampleJson = {"id":"MDc6","name":"M1","creator":{"login":"vlgunarathne","url":"https://github.com/vlgunarathne"}};

    var converted, err = <Project>sampleJson;
    println(converted);
    print(err);
}


public struct Project {
    string id;
    string name;
    Creator creator;
}

public struct Creator {
    string login;
    string url;
}
```
Here the structs are in the same .bal file 
If these structs are moved to a different package,

```
import org.wso2.structs;
public function main (string[] args) {
    json sampleJson = {"id":"MDc6","name":"M1","creator":{"login":"vlgunarathne","url":"https://github.com/vlgunarathne"}};

    var converted, err = <structs:Project>sampleJson;
    println(converted);
    print(err);
}
```
The following error occurs:
```
{msg:"cannot convert 'json' to type 'org.wso2.structs:Project': null", cause:null, stackTrace:[{caller:"main", packageName:"samples", fileName:"SampleMain.bal", lineNumber:11}], sourceType:"json", targetType:"org.wso2.structs:Project"}
```
**Affected Versions:**
0.962.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by SupunS**
## Purpose
Resolves #4736, #4757, #4926

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java [hunk 1]
```diff
@@ -98,17 +95,4 @@ public static BallerinaServerConnector getBallerinaServerConnector(Context conte
...
-    /**
-     * This method is used to convert a JSON to struct given the resource, json and required struct type.
-     *
-     * @param resource   to get required details
-     * @param bJson      which needs to be converted
-     * @param structType of required struct
-     * @return converted struct
-     */
-    public static BStruct convertJSONToStruct(Resource resource, BJSON bJson, BType structType) {
-        PackageInfo packageInfo = getPackageInfo(resource);
```
Comment (chamil321) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: I think now "getPackageInfo()" method has only one usage. It is used in "createAndGetStruct()" in StructHelper class. Shall we move the content of "getPackageInfo()" and remove it?

Comment (sameera-jayasoma) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: +1

Comment (SupunS) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: +1. 
There's another struct utils class `BLangVMStructs` which has helper methods for structs. I think the content of `StructHelper` class should also be moved to that. 
So shall we do those cleanups separately? We can do that as a part of the ongoing refactoring..

Comment (chamil321) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: +1

Comment (chamil321) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: StructHelper class is from connector directory and deals with connector related stuff. So moving it inside the org.ballerinalang.bre.bvm with all the connector-related imports might not be good. 
WDYT?

Comment (SupunS) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: AFAIU, `ConnectorUtils` is the connector helper class which contains connector specific stuff. And `StructHelper` is a helper to that helper, which contains only struct related operations. :)

Comment (chamil321) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/ConnectorUtils.java]: You are correct. :) That's because resource info is not visible to the ConnectorUtils. It gets the help from StructHelper class Which is in the same package with BResource to access it.
