### PR TITLE
Fix #4338: stop all server connectors if one fails to start up 

### LINKED ISSUE #4338: [HTTP] If a service fails to start, the already started services should also be stopped
**Description:**
Currently, services can start and run as long as there is at least one service functioning properly. The behviour should be that even if one service fails to start, the runtime should exit after stopping all the already started services.

### PR DESCRIPTION
**Pull request by pubudu91**
## Automation tests
 N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? no

### CODE REVIEW

File: stdlib/ballerina-http/src/main/java/org/ballerinalang/net/http/util/ConnectorStartupSynchronizer.java [hunk 1]
```diff
@@ -30,22 +33,37 @@
  */
 public class ConnectorStartupSynchronizer {
 
+    private List<String> inUseConnectors = new ArrayList<>();
     private Map<String, Exception> exceptions = new HashMap<>();
     private CountDownLatch countDownLatch;
```
Comment (shafreenAnfar) [inline stdlib/ballerina-http/src/main/java/org/ballerinalang/net/http/util/ConnectorStartupSynchronizer.java]: shall we give a proper name for this variable. Maybe serviceLatch ??
