### PR TITLE
Fix invalid completion with succeeding characters

### LINKED ISSUE #4870: [Language-Server] Invalid or no suggestions when a succeeding character is there.
**Description:**
Wrong or no suggestions given when there is a succeeding character.
screen shot 2018-02-26 at 11 18 53 am
screen shot 2018-02-26 at 11 19 21 am
screen shot 2018-02-26 at 11 19 34 am
screen shot 2018-02-26 at 11 19 42 am

In the above screenshots, it can be seen that when there is nothing infront of the suggestion cursor, it gives the right suggestions.

**Steps to reproduce:**
See the screenshots in order.

**Affected Versions:**
v0.961.1.SNAPSHOT

**OS, DB, other environment details and versions:**
MAC

### PR DESCRIPTION
**Pull request by nadeeshaan**
invocation symbol such as ":" or ".". Resolves #4870 

ezgif com-video-to-gif

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/filters/PackageActionFunctionAndTypesFilter.java [hunk 1]
```diff
@@ -259,21 +260,16 @@ private boolean isConnectorInit(int startIndex, TextDocumentServiceContext conte
...
-                } else {
-                    searchTokenIndex -= 1;
-                }
-            }
+        /*
+        In order to avoid the token index inconsistencies, current token index offsets from two default tokens
+         */
+        Token offsetToken = CommonUtil.getNthDefaultTokensToLeft(tokenStream, searchTokenIndex, 2);
+        if (!terminalTokens.contains(offsetToken.getText())) {
+            searchTokenIndex = offsetToken.getTokenIndex();
```
Comment (NipunaMarcus) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/filters/PackageActionFunctionAndTypesFilter.java]: this is same code as the file above. Is there a way to reuse these as a utils?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/filters/PackageActionFunctionAndTypesFilter.java]: This section is still improving. So the logic can be different with the new use-cases. So ATM I think it would be better we keep this as it is, otherwise, in the future, we might need to revert it back
